#!/usr/bin/python


class Solution(object):
    def strStr(self, haystack, needle):
        """

        RUNTIME: 59, 65, 49, 65, 38

        :type haystack: str
        :type needle: str
        :rtype: int
        """
        if len(needle) > len(haystack):
            return -1
        if not needle:
            return 0
        if not haystack:
            return -1

        for i in xrange(len(haystack)-len(needle)+1):
            found = True
            for j in xrange(len(needle)):
                if haystack[i+j] != needle[j]:
                    found = False
                    break
            if found:
                return i
        return -1


s = Solution()
x = 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbcc'
y = 'aabbcc'
assert s.strStr(x, y) == 208

x = 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbcc'
assert s.strStr(x, y) == 1912

x = 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbcc'
assert s.strStr(x, y) == 6385

x = 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbc'
for _ in xrange(10):
    x += x
x += 'ababababbbababaaaaabababababaaaababababaabaaaababababbaabaaaabaaaabababbbabbababbbbabababababababababaaabababaabbabaabbaababbababaabababababababababababababaaaaaabbbbababaabababababaaabaabbacbcbacbabcabaaaabbaabbcc'
assert s.strStr(x, y) == 218320
